version: "3"
services:
  mongo:
    image: mongo:3.4.4
    ports:
      - "27017:27017"
      - "28017:28017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs0", "--httpinterface", "--rest" ]
    networks:
      - dbnet

  mongosetup:
    image: mongo:3.4.4
    depends_on:
      - mongo
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ]
    networks:
      - dbnet

  elasticsearch:
    image: elasticsearch:5.4
    ports:
      - "9200:9200"
    networks:
      - dbnet

  connector:
    image: yeasy/mongo-connector
    depends_on:
      - mongosetup
      - elasticsearch
    networks:
      - dbnet

networks:
  dbnet: