version: "3"
services:
  mongo:
    image: mongo:3.4.4
    ports:
      - "27017:27017"
      - "28017:28017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs0", "--httpinterface", "--rest" ]
    networks:
      - dbnet

  elasticsearch:
    image: elasticsearch:5.4
    ports:
      - "9200:9200"
    networks:
      - dbnet
  
  setup:
    build: .
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - dbnet
      
  connector:
    image: python:3.6
    depends_on:
      - setup
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/mongo-connector.sh" ]
    networks:
      - dbnet

networks:
  dbnet: